;Draw the tree illustrating the process generated by the count-change procedure
;of sectiong1.1.2 in making change of 11 cents. What are the orders of growth
;of the space and number of steps used by this process as the amount to be
;changed increases?
(define (count-change amount)
  (cc amount 5))
(define (cc amount kinds-of-coins)
  (cond ((= amount 0) 1)
        ((or (< amount 0) (= kinds-of-coins 0)) 0)
        (else (+ (cc amount (- kinds-of-coins 1))
              (cc (- amount (first-denomination kinds-of-coins))
                  kinds-of-coins)))))
(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

;*************Solution*************
;(amount kinds-of-coins) pair
;(11 5)
;left: (11 4)
;        left: (11 3)
;                left: (11 2)
;                        left: (11 1)
;                                    left: (11 0) 0
;                                    right: (10 1)
;                                            left: (10 0) 0
;                                            right: (9 1)
;                                                    ......
;                                                            right: (1 1)
;                                                                    left: (1 0) 0
;                                                                    right: (0 1) 1
;                        right: (6 2)
;                                left: (6 1)
;                                        ......
;                                                right: (1 1)
;                                                        left: (1 0) 0
;                                                        right: (0 1) 1
;                                right: (1 2)
;                                        left: (1 1)
;                                                left: (1 0) 0
;                                                right: (0 1) 1
;                                        right: (-4 2) 0
;                right: (1 3)
;                        left: (1 2)
;                                left: (1 1)
;                                        left: (1 0) 0
;                                        right: (0 1) 1
;                                right: (-4 2) 0
;                        right: (-9 3) 0
;        right: (-14 4) 0
;right: (-39 5) 0
;return 4

;space O(n)
;steps(time) O(n^5)

;small changes can be made:
(define (cc amount kinds-of-coins)
  (cond ((or (= amount 0) (= kinds-of-coins 1) 1))
        ((or (< amount 0) (= kinds-of-coins 0)) 0)
        (else (+ (cc amount (- kinds-of-coins 1))
              (cc (- amount (first-denomination kinds-of-coins))
                  kinds-of-coins)))))